"""all tables but some relations

Revision ID: f7f27cbaecc7
Revises: f131831e3e51
Create Date: 2024-07-25 18:00:50.586091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7f27cbaecc7'
down_revision = 'f131831e3e51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_client_created_at'), ['created_at'], unique=False)

    op.create_table('suplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('suplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suplier_created_at'), ['created_at'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=64), nullable=False),
    sa.Column('password', sa.String(length=64), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)

    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suplier_id', sa.Integer(), nullable=False),
    sa.Column('document_number', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('total_amount_sale', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['suplier_id'], ['suplier.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_suplier_id'), ['suplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_user_id'), ['user_id'], unique=False)

    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('client_doc_number', sa.Integer(), nullable=False),
    sa.Column('client_doc_name', sa.String(length=64), nullable=False),
    sa.Column('recived_money', sa.Float(), nullable=False),
    sa.Column('change_money', sa.Float(), nullable=False),
    sa.Column('total_amount_sale', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_user_id'), ['user_id'], unique=False)

    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('total_amount_sale', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=64), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_sale_id'), ['sale_id'], unique=False)

    op.create_table('purchase_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchase.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_detail_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_detail_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_detail_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('sale_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('price_sale', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('sub_total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sale.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_detail', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_detail_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_detail_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sale_detail_sale_id'), ['sale_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_detail_sale_id'))
        batch_op.drop_index(batch_op.f('ix_sale_detail_product_id'))
        batch_op.drop_index(batch_op.f('ix_sale_detail_created_at'))

    op.drop_table('sale_detail')
    with op.batch_alter_table('purchase_detail', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_detail_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_detail_product_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_detail_created_at'))

    op.drop_table('purchase_detail')
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_sale_id'))
        batch_op.drop_index(batch_op.f('ix_invoice_created_at'))

    op.drop_table('invoice')
    with op.batch_alter_table('sale', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_user_id'))
        batch_op.drop_index(batch_op.f('ix_sale_created_at'))
        batch_op.drop_index(batch_op.f('ix_sale_client_id'))

    op.drop_table('sale')
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_suplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_created_at'))

    op.drop_table('purchase')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    with op.batch_alter_table('suplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suplier_created_at'))

    op.drop_table('suplier')
    with op.batch_alter_table('client', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_client_created_at'))

    op.drop_table('client')
    # ### end Alembic commands ###
